version: '2'
services:
  app:
    image: rmts/app:7.4-ubuntu20
    volumes:
      - ./:/var/www/html:cached
      - ~/.ssh:/root/.ssh:cached
      - /tmp
    ports:
      - "20211:22"
    environment:
      - QUEUE_WORKER=app-default.conf
      - "VIRTUAL_HOST=laravel-akamai.lvh.me"
    networks:
      - laravel-akamai-net
      - nginx-proxy

  redis:
    image: redis:5-alpine
    networks:
      - laravel-akamai-net

networks:
  laravel-akamai-net:
    driver: bridge
  nginx-proxy:
    external:
      name: docker_default
