name: run-tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [7.2, 7.3, 7.4]
        laravel: [6.*]
        include:
          -   laravel: 6.*
              testbench: 4.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      -   name: Checkout code
          uses: actions/checkout@v1

      -   name: Cache dependencies
          uses: actions/cache@v1
          with:
            path: ~/.composer/cache/files
            key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, php-redis
          coverage: none
          tools: php-cs-fixer, phpunit, prestissimo

      -   name: Install dependencies
          run: |
            composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
            composer update --prefer-dist --no-interaction --no-suggest

      -   name: Execute tests
          run: vendor/bin/phpunit
